/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */import java.awt.FlowLayout;
import java.sql.DriverManager;
import javax.swing.*;
import javax.sql.*;
import java.util.Date;
import java.util.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Suhas
 */
public class Update_Product extends javax.swing.JFrame {
Date d;
    Connection cn;
ResultSet rs;
Statement stat;
String s;
    /**
     * Creates new form Update_Product
     */
    public Update_Product() {
               try{
        initComponents();
        
        jLabel7=new JLabel(new ImageIcon("main.png"));
        jLabel7.setLayout(new FlowLayout());
        this.add(jLabel7);
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
                   d=new java.util.Date();
            jLabel13.setText(new SimpleDateFormat("yyyy-MM-dd").format(d));       
       
        this.setTitle("Wholesale_management");
        s=(JOptionPane.showInputDialog("ENTER PRODUCT ID TO UPDATE")).trim();
        Class.forName("com.mysql.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wholesale_management","root","root");
        stat=cn.createStatement();
        rs=stat.executeQuery("select * from product where p_id="+s+"");
          
        if(rs.first())
        {
            this.setVisible(true);  
        rs.first();
                jTextField1.setText(""+rs.getInt(1));
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(3));
                jTextField4.setText(rs.getString(4));
                jTextField5.setText(rs.getString(5));
        }  
        else
        {
            JOptionPane.showMessageDialog(null, "PRODUCT NOT FOUND...");
            this.dispose();
            new add_product().setVisible(true);
        }
        }catch(NullPointerException e){
        new add_product().setVisible(true);}
        catch(SQLSyntaxErrorException e){JOptionPane.showMessageDialog(null, "ENTER VALID INPUT");
        this.dispose();
        new add_product().setVisible(true);
        }       
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("PRODUCT ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(139, 144, 249, 46);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("PRODUCT RATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(139, 312, 249, 46);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(421, 144, 821, 46);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(421, 230, 821, 46);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(421, 312, 821, 46);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("PRODUCT QUANTITY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(139, 392, 249, 46);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(421, 392, 821, 46);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("PRODUCT BILL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(139, 471, 249, 46);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField5MouseEntered(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(421, 471, 821, 46);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("PRODUCT NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(139, 230, 249, 46);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(421, 590, 304, 57);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(842, 590, 281, 57);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE PRODUCT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(421, 34, 600, 60);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("DATE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1060, 10, 88, 38);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1160, 10, 173, 38);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -10, 1460, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    add_product ap=new add_product();
    ap.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    try{
        String p_rate,p_quantity,p_bill,p_av_quan;
                
                p_rate=jTextField3.getText();
                p_quantity=jTextField4.getText();
                p_bill=jTextField5.getText();
               
                
        if(p_rate.trim().length()==0||p_quantity.trim().length()==0||p_bill.trim().length()==0)
            JOptionPane.showMessageDialog(null,"ENTER ALL INFORMATION!");
        else
        {
            stat.executeUpdate("update product set p_rate='"+p_rate+"',p_quantity='"+p_quantity+"',p_bill='"+p_bill+"',p_av_quantity='"+p_quantity+"' where p_id="+s+"");
            JOptionPane.showMessageDialog(null,"INFORMATION UPDATED SUCCESSFULLY","",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new add_product().setVisible(true);
        }
    }catch(Exception e){JOptionPane.showMessageDialog(null, e);
            this.dispose();
            new add_product().setVisible(true);
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased

                char z=evt.getKeyChar();
        String x;
        if(evt.getKeyCode()==10||evt.getKeyCode()==8)
        {
        }
        else if(z>='0'&&z<='9')
        {
            x=jTextField4.getText();
            jTextField4.setText(x);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ONLY NUMBER INPUT");
            jTextField4.setText("");         
        }
        
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased

                char z=evt.getKeyChar();
        String x;
        if(evt.getKeyCode()==10||evt.getKeyCode()==8)
        {
        }
        else if(z>='0'&&z<='9')
        {
            x=jTextField3.getText();
            jTextField3.setText(x);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ONLY NUMBER INPUT");
            jTextField3.setText("");         
        }        
        
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseEntered
    double x,y;
        x=Double.valueOf(jTextField3.getText());
        y=Double.valueOf(jTextField4.getText());
        jTextField5.setText(""+(x*y));
    }//GEN-LAST:event_jTextField5MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 new Update_Product();
        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
